name: Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          brew install dpkg

      - name: Build flexdecrypt
        run: ./Scripts/build-iphoneos-arm.sh

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: ./*.deb
          tag_name: Test
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
